addSbtPlugin("ch.epfl.scala"         % "sbt-bloop"    % "1.4.8")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("com.github.sbt"        % "sbt-jacoco"   % "3.3.0")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"   % "7.4.0")
addSbtPlugin("bujo"                  % "sbt-schemaupdater" % "0.1.1-SNAPSHOT")
